# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [3]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [6]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [7]:
# Create a 1-dimensional NumPy array using np.array()
one_d_array = np.array([1,2,3])
print(one_d_array)
# Create a 2-dimensional NumPy array using np.array()
two_d_array = np.array([[1,2,4],[3,4,5]])
print(two_d_array)
# Create a 3-dimensional Numpy array using np.array()
three_d_array = np.array([[[1,2,3],
                           [4,5,6]],
                           [[9,8,7],
                            [1,2,3]]])
print(three_d_array)

[1 2 3]
[[1 2 4]
 [3 4 5]]
[[[1 2 3]
  [4 5 6]]

 [[9 8 7]
  [1 2 3]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [8]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
one_d_array.shape, one_d_array.ndim, one_d_array.size, type(one_d_array)

((3,), 1, 3, numpy.ndarray)

In [ ]:
# Attributes of 2-dimensional array


In [ ]:
# Attributes of 3-dimensional array


In [15]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
two_d_to_pandas = pd.DataFrame(two_d_array)
display(two_d_to_pandas)

0  1  2
0  1  2  4
1  3  4  5

In [17]:
# Create an array of shape (10, 2) with only ones
random_array_1 = np.ones(shape=(10,2))

In [18]:
random_array_1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
# Create an array of shape (7, 2, 3) of only zeros
random_array_2 = np.zeros(shape=(7,2,3))

In [20]:
random_array_2

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
import matplotlib.pyplot as plt


In [22]:
random_array_2.shape

(7, 2, 3)

In [23]:
random_array_2.ndim

3

In [29]:
# Create an array within a range of 0 and 100 with step 3
random_array_3 = np.arange(0,100,3)

In [30]:
random_array_3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [33]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array_4 = np.random.randint(10,size=(7,2))

In [34]:
random_array_4

array([[1, 0],
       [5, 3],
       [6, 0],
       [4, 1],
       [2, 2],
       [1, 4],
       [7, 7]])

In [38]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_5 = np.random.random((3,5))

In [39]:
random_array_5

array([[0.13576515, 0.87252305, 0.33958627, 0.26830948, 0.95967612],
       [0.57064766, 0.75591189, 0.80542679, 0.88369539, 0.51228468],
       [0.91994824, 0.52403376, 0.27804388, 0.19948409, 0.55041964]])

In [41]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_6 = np.random.randint(0,10,size=(4,6))

In [43]:
random_array_6

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [47]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable


# Find the unique numbers in the array you just created
np.unique(random_array_6)

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [49]:
# Find the 0'th index of the latest array you created
random_array_6[0]

array([6, 3, 7, 4, 6, 9])

In [50]:
# Get the first 2 rows of latest array you created
random_array_6[:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [52]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_6[:2,:2]

array([[6, 3],
       [2, 6]])

In [59]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_10 = np.random.randint(0,10, size=(3,5))
random_array_11 = np.ones((3,5))


In [55]:
random_array_10

array([[3, 8, 1, 9, 8],
       [9, 4, 1, 3, 6],
       [7, 2, 0, 3, 1]])

In [64]:
a0 = np.ones((3,5))

In [62]:
# Add the two arrays together
random_array_10 + random_array_11

array([[ 8.,  8.,  3.,  1.,  8.],
       [ 3.,  3.,  1.,  5., 10.],
       [ 7., 10.,  9.,  7.,  9.]])

In [63]:
# Create another array of ones of shape (5, 3)
a1 = np.ones((5,3))

In [66]:
# Try add the array of ones and the other most recent array together
a0.T+a1

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [71]:
# Create another array of ones of shape (3, 5)
a3 = np.random.randint(0,10,size=(3,5))

In [72]:
a3

array([[7, 1, 0, 6, 6],
       [7, 4, 2, 7, 5],
       [2, 0, 2, 4, 2]])

In [ ]:
# Subtract the new array of ones from the other most recent array


In [ ]:
# Multiply the ones array with the latest array


In [ ]:
# Take the latest array to the power of 2 using '**'


In [ ]:
# Do the same thing with np.square()


In [73]:
# Find the mean of the latest array using np.mean()
a3.mean()

np.float64(3.6666666666666665)

In [74]:
# Find the maximum of the latest array using np.max()
np.max(a3)

np.int64(7)

In [ ]:
# Find the minimum of the latest array using np.min()


In [75]:
# Find the standard deviation of the latest array
np.std(a3)

np.float64(2.467567403109566)

In [ ]:
# Find the variance of the latest array


In [78]:
# Reshape the latest array to (3, 5, 1)
a3.reshape(3, 5, 1)

array([[[7],
        [1],
        [0],
        [6],
        [6]],

       [[7],
        [4],
        [2],
        [7],
        [5]],

       [[2],
        [0],
        [2],
        [4],
        [2]]])

In [79]:
# Transpose the latest array
a3.T

array([[7, 7, 2],
       [1, 4, 0],
       [0, 2, 2],
       [6, 7, 4],
       [6, 5, 2]])

What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [ ]:
# Perform a dot product on the two newest arrays you created


In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [ ]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [82]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a5 = np.random.randint(0,10,size=(5,3))
a6 = np.random.randint(0,10,size=(5,3))

In [83]:
# Compare the two arrays with '>'
a5 > a6

array([[ True,  True, False],
       [False,  True, False],
       [ True,  True, False],
       [False, False,  True],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

In [84]:
# Compare the two arrays with '>='
a5 >= a6

array([[ True,  True, False],
       [False,  True, False],
       [ True,  True, False],
       [False, False,  True],
       [ True,  True, False]])

In [85]:
# Find which elements of the first array are greater than 7
a5 > 7

array([[False, False, False],
       [False, False, False],
       [ True,  True, False],
       [False, False,  True],
       [False,  True, False]])

In [86]:
# Which parts of each array are equal? (try using '==')
a5 == a6

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [88]:
a5

array([[6, 3, 6],
       [2, 5, 1],
       [9, 8, 4],
       [5, 3, 9],
       [6, 8, 6]])

In [87]:
# Sort one of the arrays you just created in ascending order
np.sort(a5)

array([[3, 6, 6],
       [1, 2, 5],
       [4, 8, 9],
       [3, 5, 9],
       [6, 6, 8]])

In [89]:
# Sort the indexes of one of the arrays you just created
np.argsort(a5)

array([[1, 0, 2],
       [2, 0, 1],
       [2, 1, 0],
       [1, 0, 2],
       [0, 2, 1]])

In [ ]:
# Find the index with the maximum value in one of the arrays you've created


In [ ]:
# Find the index with the minimum value in one of the arrays you've created


In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [93]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(a5, axis=1)

array([0, 1, 0, 2, 1])

In [91]:
a5

array([[6, 3, 6],
       [2, 5, 1],
       [9, 8, 4],
       [5, 3, 9],
       [6, 8, 6]])

In [90]:
# Create an array of normally distributed random numbers
np.random.randn(5,3)

array([[ 0.45293633, -0.16606091,  0.21493883],
       [-2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183],
       [-0.99258618,  0.10234768, -0.43260928],
       [-0.6591823 ,  0.0039373 ,  0.4777541 ]])

In [96]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.